services:
  # Backend API Service
  - type: web
    name: sales-scoreboard-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://sales-scoreboard-client.onrender.com
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health

  # Frontend Client Service
  - type: web
    name: sales-scoreboard-client
    env: static
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://sales-scoreboard-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
